
services:
  - type: web
    name: maintai-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    rootDir: backend
    envVars:
      - key: FLASK_ENV
        value: production

  - type: static
    name: maintai-frontend
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
